/**
 * Report generator for creating markdown reports from metrics
 */

import type { PackageMetrics, DetailedStats } from './types';

export interface ReportOptions {
  /** Report title */
  title?: string;
  /** Include daily breakdown tables */
  includeDailyBreakdown?: boolean;
  /** Include growth trends */
  includeTrends?: boolean;
}

/**
 * Generate a markdown report from package metrics.
 * 
 * @param metrics - Array of package metrics
 * @param options - Report configuration
 * @returns Markdown-formatted report
 * 
 * @example
 * ```typescript
 * const metrics = await collector.getBatchMetrics(['@sfsec/core']);
 * const report = generateReport(metrics, { title: 'Monthly Report' });
 * fs.writeFileSync('report.md', report);
 * ```
 */
export function generateReport(
  metrics: PackageMetrics[],
  options: ReportOptions = {}
): string {
  const { title = 'NPM Download Metrics Report', includeTrends = true } = options;

  const lines: string[] = [];

  // Header
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`**Generated:** ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}`);
  lines.push('');

  if (metrics.length === 0) {
    lines.push('*No metrics available*');
    return lines.join('\n');
  }

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Package | Last Day | Last Week | Last Month | Last Year |');
  lines.push('|---------|----------|-----------|------------|-----------|');

  metrics.forEach(metric => {
    lines.push(
      `| ${metric.package} | ${formatNumber(metric.lastDay)} | ${formatNumber(
        metric.lastWeek
      )} | ${formatNumber(metric.lastMonth)} | ${formatNumber(metric.lastYear)} |`
    );
  });

  // Totals row
  const totals = calculateTotals(metrics);
  lines.push(
    `| **Total** | **${formatNumber(totals.lastDay)}** | **${formatNumber(
      totals.lastWeek
    )}** | **${formatNumber(totals.lastMonth)}** | **${formatNumber(totals.lastYear)}** |`
  );
  lines.push('');

  // Trends
  if (includeTrends) {
    lines.push('## Growth Trends');
    lines.push('');

    metrics.forEach(metric => {
      lines.push(`### ${metric.package}`);
      lines.push('');

      const weeklyGrowth = calculateGrowth(metric.lastWeek, metric.lastMonth / 4.33);
      const monthlyGrowth = calculateGrowth(metric.lastMonth, metric.lastYear / 12);

      lines.push(`- **Weekly trend:** ${formatGrowth(weeklyGrowth)}`);
      lines.push(`- **Monthly trend:** ${formatGrowth(monthlyGrowth)}`);
      lines.push('');
    });
  }

  // Package details
  lines.push('## Package Details');
  lines.push('');

  metrics.forEach(metric => {
    lines.push(`### ${metric.package}`);
    lines.push('');
    lines.push('| Period | Downloads |');
    lines.push('|--------|-----------|');
    lines.push(`| Last 24 hours | ${formatNumber(metric.lastDay)} |`);
    lines.push(`| Last 7 days | ${formatNumber(metric.lastWeek)} |`);
    lines.push(`| Last 30 days | ${formatNumber(metric.lastMonth)} |`);
    lines.push(`| Last 365 days | ${formatNumber(metric.lastYear)} |`);
    lines.push('');

    // Average calculations
    const avgPerDay = Math.round(metric.lastYear / 365);
    const avgPerWeek = Math.round(metric.lastYear / 52);
    const avgPerMonth = Math.round(metric.lastYear / 12);

    lines.push('**Averages:**');
    lines.push(`- Per day: ~${formatNumber(avgPerDay)}`);
    lines.push(`- Per week: ~${formatNumber(avgPerWeek)}`);
    lines.push(`- Per month: ~${formatNumber(avgPerMonth)}`);
    lines.push('');
  });

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Report generated by @sfsec/metrics*');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate a detailed report with daily breakdowns.
 * 
 * @param detailedStats - Array of detailed statistics
 * @param options - Report configuration
 * @returns Markdown-formatted detailed report
 */
export function generateDetailedReport(
  detailedStats: DetailedStats[],
  options: ReportOptions = {}
): string {
  const { title = 'Detailed NPM Download Report' } = options;

  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`**Generated:** ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}`);
  lines.push('');

  detailedStats.forEach(stats => {
    lines.push(`## ${stats.package}`);
    lines.push('');
    lines.push(`**Period:** ${stats.start} to ${stats.end}`);
    lines.push(`**Total Downloads:** ${formatNumber(stats.downloads)}`);
    lines.push('');

    if (stats.downloads_per_day && stats.downloads_per_day.length > 0) {
      lines.push('### Daily Breakdown');
      lines.push('');
      lines.push('| Date | Downloads |');
      lines.push('|------|-----------|');

      // Sort by date descending
      const sorted = [...stats.downloads_per_day].sort((a, b) => b.day.localeCompare(a.day));
      
      sorted.forEach(day => {
        lines.push(`| ${day.day} | ${formatNumber(day.downloads)} |`);
      });

      lines.push('');

      // Statistics
      const dailyDownloads = stats.downloads_per_day.map(d => d.downloads);
      const avg = Math.round(dailyDownloads.reduce((a, b) => a + b, 0) / dailyDownloads.length);
      const max = Math.max(...dailyDownloads);
      const min = Math.min(...dailyDownloads);

      lines.push('**Statistics:**');
      lines.push(`- Average: ${formatNumber(avg)} downloads/day`);
      lines.push(`- Peak: ${formatNumber(max)} downloads`);
      lines.push(`- Low: ${formatNumber(min)} downloads`);
      lines.push('');
    }
  });

  lines.push('---');
  lines.push('');
  lines.push('*Report generated by @sfsec/metrics*');
  lines.push('');

  return lines.join('\n');
}

/**
 * Format number with commas.
 */
function formatNumber(num: number): string {
  return num.toLocaleString('en-US');
}

/**
 * Calculate growth percentage.
 */
function calculateGrowth(current: number, previous: number): number {
  if (previous === 0) return current > 0 ? 100 : 0;
  return ((current - previous) / previous) * 100;
}

/**
 * Format growth percentage with emoji indicators.
 */
function formatGrowth(growth: number): string {
  const formatted = `${growth >= 0 ? '+' : ''}${growth.toFixed(1)}%`;
  
  if (growth > 20) return `📈 ${formatted} (strong growth)`;
  if (growth > 5) return `↗️ ${formatted} (growth)`;
  if (growth > -5) return `➡️ ${formatted} (stable)`;
  if (growth > -20) return `↘️ ${formatted} (decline)`;
  return `📉 ${formatted} (strong decline)`;
}

/**
 * Calculate totals across all packages.
 */
function calculateTotals(metrics: PackageMetrics[]): PackageMetrics {
  return metrics.reduce(
    (acc, curr) => ({
      package: 'Total',
      lastDay: acc.lastDay + curr.lastDay,
      lastWeek: acc.lastWeek + curr.lastWeek,
      lastMonth: acc.lastMonth + curr.lastMonth,
      lastYear: acc.lastYear + curr.lastYear,
      fetchedAt: acc.fetchedAt,
    }),
    {
      package: 'Total',
      lastDay: 0,
      lastWeek: 0,
      lastMonth: 0,
      lastYear: 0,
      fetchedAt: new Date().toISOString(),
    }
  );
}
