import { describe, it, expect } from 'vitest';
import { generateReport, generateDetailedReport } from '../src/reporter';
import type { PackageMetrics, DetailedStats } from '../src/types';

describe('generateReport', () => {
  const mockMetrics: PackageMetrics[] = [
    {
      package: '@sfsec/core',
      lastDay: 100,
      lastWeek: 750,
      lastMonth: 3200,
      lastYear: 38000,
      fetchedAt: '2026-04-07T08:00:00.000Z',
    },
    {
      package: '@sfsec/security',
      lastDay: 80,
      lastWeek: 600,
      lastMonth: 2500,
      lastYear: 30000,
      fetchedAt: '2026-04-07T08:00:00.000Z',
    },
  ];

  it('should generate a basic markdown report', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('# NPM Download Metrics Report');
    expect(report).toContain('## Summary');
    expect(report).toContain('@sfsec/core');
    expect(report).toContain('@sfsec/security');
  });

  it('should include custom title', () => {
    const report = generateReport(mockMetrics, { title: 'Monthly Report' });

    expect(report).toContain('# Monthly Report');
    expect(report).not.toContain('NPM Download Metrics Report');
  });

  it('should create summary table', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('| Package | Last Day | Last Week | Last Month | Last Year |');
    expect(report).toContain('|---------|----------|-----------|------------|-----------|');
    expect(report).toContain('| @sfsec/core | 100 | 750 | 3,200 | 38,000 |');
  });

  it('should calculate and display totals', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('| **Total** | **180** | **1,350** | **5,700** | **68,000** |');
  });

  it('should include growth trends when enabled', () => {
    const report = generateReport(mockMetrics, { includeTrends: true });

    expect(report).toContain('## Growth Trends');
    expect(report).toContain('Weekly trend:');
    expect(report).toContain('Monthly trend:');
  });

  it('should exclude growth trends when disabled', () => {
    const report = generateReport(mockMetrics, { includeTrends: false });

    expect(report).not.toContain('## Growth Trends');
  });

  it('should include package details section', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('## Package Details');
    expect(report).toContain('### @sfsec/core');
    expect(report).toContain('| Period | Downloads |');
    expect(report).toContain('| Last 24 hours | 100 |');
    expect(report).toContain('| Last 7 days | 750 |');
  });

  it('should calculate averages', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('**Averages:**');
    expect(report).toContain('Per day:');
    expect(report).toContain('Per week:');
    expect(report).toContain('Per month:');
  });

  it('should include generation timestamp', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('**Generated:**');
  });

  it('should include footer', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('*Report generated by @sfsec/metrics*');
  });

  it('should handle empty metrics array', () => {
    const report = generateReport([]);

    expect(report).toContain('*No metrics available*');
  });

  it('should format numbers with commas', () => {
    const report = generateReport(mockMetrics);

    expect(report).toContain('3,200');
    expect(report).toContain('38,000');
  });

  it('should use emoji indicators for growth trends', () => {
    const report = generateReport(mockMetrics, { includeTrends: true });

    // Should contain at least one growth indicator
    expect(report).toMatch(/[📈↗️➡️↘️📉]/);
  });
});

describe('generateDetailedReport', () => {
  const mockDetailedStats: DetailedStats[] = [
    {
      package: '@sfsec/core',
      downloads: 850,
      start: '2026-04-01',
      end: '2026-04-07',
      downloads_per_day: [
        { downloads: 100, day: '2026-04-01' },
        { downloads: 120, day: '2026-04-02' },
        { downloads: 130, day: '2026-04-03' },
        { downloads: 125, day: '2026-04-04' },
        { downloads: 115, day: '2026-04-05' },
        { downloads: 140, day: '2026-04-06' },
        { downloads: 120, day: '2026-04-07' },
      ],
    },
  ];

  it('should generate detailed markdown report', () => {
    const report = generateDetailedReport(mockDetailedStats);

    expect(report).toContain('# Detailed NPM Download Report');
    expect(report).toContain('## @sfsec/core');
  });

  it('should include custom title', () => {
    const report = generateDetailedReport(mockDetailedStats, {
      title: 'Custom Detailed Report',
    });

    expect(report).toContain('# Custom Detailed Report');
  });

  it('should display period and total downloads', () => {
    const report = generateDetailedReport(mockDetailedStats);

    expect(report).toContain('**Period:** 2026-04-01 to 2026-04-07');
    expect(report).toContain('**Total Downloads:** 850');
  });

  it('should include daily breakdown table', () => {
    const report = generateDetailedReport(mockDetailedStats);

    expect(report).toContain('### Daily Breakdown');
    expect(report).toContain('| Date | Downloads |');
    expect(report).toContain('| 2026-04-01 | 100 |');
    expect(report).toContain('| 2026-04-07 | 120 |');
  });

  it('should sort daily breakdown by date descending', () => {
    const report = generateDetailedReport(mockDetailedStats);

    const lines = report.split('\n');
    const dateLines = lines.filter(line => line.includes('2026-04-'));

    // First date line should be most recent
    expect(dateLines[0]).toContain('2026-04-07');
  });

  it('should calculate and display statistics', () => {
    const report = generateDetailedReport(mockDetailedStats);

    expect(report).toContain('**Statistics:**');
    expect(report).toContain('Average:');
    expect(report).toContain('Peak:');
    expect(report).toContain('Low:');
  });

  it('should handle stats without daily breakdown', () => {
    const statsWithoutDaily: DetailedStats[] = [
      {
        package: '@sfsec/core',
        downloads: 500,
        start: '2026-04-07',
        end: '2026-04-07',
      },
    ];

    const report = generateDetailedReport(statsWithoutDaily);

    expect(report).toContain('@sfsec/core');
    expect(report).toContain('**Total Downloads:** 500');
    expect(report).not.toContain('### Daily Breakdown');
  });

  it('should handle multiple packages', () => {
    const multipleStats: DetailedStats[] = [
      ...mockDetailedStats,
      {
        package: '@sfsec/security',
        downloads: 600,
        start: '2026-04-01',
        end: '2026-04-07',
        downloads_per_day: [
          { downloads: 85, day: '2026-04-01' },
          { downloads: 90, day: '2026-04-02' },
        ],
      },
    ];

    const report = generateDetailedReport(multipleStats);

    expect(report).toContain('## @sfsec/core');
    expect(report).toContain('## @sfsec/security');
  });

  it('should include footer', () => {
    const report = generateDetailedReport(mockDetailedStats);

    expect(report).toContain('*Report generated by @sfsec/metrics*');
  });

  it('should format numbers with commas', () => {
    const largeStats: DetailedStats[] = [
      {
        package: '@sfsec/core',
        downloads: 125000,
        start: '2026-01-01',
        end: '2026-04-07',
      },
    ];

    const report = generateDetailedReport(largeStats);

    expect(report).toContain('125,000');
  });
});
